### ISSUE TITLE
E14 bulb still not identified correctly

### ISSUE THREAD

**Issue by Asinke** [athombv/com.ikea.tradfri#21] opened 2017-09-23 08:01 UTC
Tested with App version 1.1.0:

Tested E14 bulb properties:
Product ID: TRADFRI bulb E14 W op/ch 400lm
Device ID: 256
Profile ID: 49246

Please let me know if you need more   ##information

**Comment by j0o5t** [comment] 2017-09-23 12:55
Same issue here, tested with app version 1.0.10

**Comment by RobinBol** [comment] 2017-09-25 12:37
Duplicate of: https://github.com/athombv/com.ikea.tradfri/issues/14

Update will be pushed soon.

**Closed by RobinBol** 2017-09-25 12:37 UTC
