### ISSUE TITLE
Tradfri LED 400LM E14 cannot be dimmed

### ISSUE THREAD

**Issue by epjjansen** [athombv/com.ikea.tradfri#12] opened 2017-09-13 18:47 UTC
Tradfri LED 400LM E14 cannot be dimmed
It shows up in Homey as unknown zigbee device

IKEA Partnumber: 603.652.71
19972 NLD
Production date: 1727
Firmware 1.2.214
Model: Pear shape
5.3 Watt
LED1649C5
2700Kelvin
D: 38mm
L: 110mm
![productid](https://user-images.githubusercontent.com/31935273/30394882-b0a3a1f0-98c4-11e7-9a59-7e99291c8097.png)

**Comment by bvdbos** [comment] 2017-09-14 06:16
@epjjansen The device-id and profile-id do matter, nothing personal about those and that's the values a device is identified with. Also, for Network Adress I don't expect this to be personal either ;-)

**Comment by epjjansen** [comment] 2017-09-14 07:53
Device ID: 256
Profile ID: 49246
![zones devices - homey](https://user-images.githubusercontent.com/31935273/30418218-90e3384e-9932-11e7-8b48-e147bbd8731e.png)

**Comment by bvdbos** [comment] 2017-09-14 08:07
Ah, that's already on Github since sept 4th, but not in the appstore yet... 
https://github.com/athombv/com.ikea.tradfri/commit/6c2e6d46e0c7a01fdf78d2bc7ba1173b9b25dc5d

You could install the latest version through the CLI or wait until it's in the appstore..

**Comment by bvdbos** [comment] 2017-09-14 08:11
Mmm, 1.0.10 is in store and should have to changes already...

**Comment by epjjansen** [comment] 2017-09-14 08:39
It has a different Product ID
"productId": "TRADFRI bulb E27 opal 1000lm" 
vs.
"productId": "TRADFRI bulb E14 W op/ch 400lm"

**Comment by Asinke** [comment] 2017-09-16 18:43
Same problem here with 3 E14 bulbs retrieved from different IKEA stores.
Devicxe information is below:

![screen shot 2017-09-16 at 20 43 37](https://user-images.githubusercontent.com/32021588/30514956-b41e9152-9b1f-11e7-9529-67eb6f949a16.png)

**Comment by RobinBol** [comment] 2017-09-18 19:10
Duplicate of https://github.com/athombv/com.ikea.tradfri/issues/14

**Closed by RobinBol** 2017-09-18 19:10 UTC
